disabled_rules:
  - trailing_whitespace
  - identifier_name
  - force_cast
  - force_try
  - nesting
  - type_name

  - file_length
  - type_body_length
  - line_length
  - cyclomatic_complexity
  - function_body_length
  - for_where
  - multiple_closures_with_trailing_closure

excluded:
  - RecycleItem+CoreDataProperties.swift
  - AppData+CoreDataProperties.swift
  - Item+CoreDataProperties.swift
  - ShoppingList+CoreDataProperties.swift
